// ============================================================
// Demo Data — Realistic synthetic data for demo mode
// ============================================================

import type {
  GlobalMetrics,
  LiveTrade,
  ClosedTrade,
  BurnRecord,
  WalletInfo,
} from '@/types';

// --- Helper ---
function daysAgo(days: number): number {
  return Math.floor(Date.now() / 1000) - days * 86400;
}

function hoursAgo(hours: number): number {
  return Math.floor(Date.now() / 1000) - hours * 3600;
}

function formatSolscanUrl(sig: string): string {
  return `https://solscan.io/tx/${sig}`;
}

// --- Demo Metrics ---
export function getDemoMetrics(): GlobalMetrics {
  return {
    totalWalletValueSol: 1450.78,
    totalWalletValueUsd: 212453.57,
    totalSolProfitGenerated: 842.5,
    lifetimeRoiPercent: 345.8,
    profitFactor: 3.21,
    winRate: 82.1,
    totalTradesClosed: 179,
    totalWins: 147,
    totalLosses: 32,
    totalTradoorBurned: 5200000,
    burnSupplyPercent: 5.2,
    taxInflowRateSolHr: 2.4,
    lastUpdated: new Date().toISOString(),
  };
}

// --- Demo Wallet ---
export function getDemoWalletInfo(): WalletInfo {
  return {
    balanceSol: 1450.78,
    balanceUsd: 212453.57,
    solPrice: 146.44,
  };
}

// --- Demo Live Trades ---
export function getDemoLiveTrades(): LiveTrade[] {
  return [
    {
      id: 'lt-001',
      tokenMint: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      tokenSymbol: 'PEPE',
      tokenName: 'Pepe',
      action: 'OPEN',
      entryTimestamp: hoursAgo(4),
      entrySolAmount: 25.0,
      entryMarketCap: 1200000,
      entryPrice: 0.0000012,
      exitTimestamp: null,
      exitSolAmount: null,
      exitMarketCap: null,
      exitPrice: null,
      netPnlSol: null,
      roiPercent: null,
      holdDurationSec: null,
      archiveTag: null,
      traderMemo: 'RIDING WHALE WALLET ROTATION',
      currentPrice: 0.00000171,
      currentMarketCap: 1710000,
      currentRoi: 42.5,
      status: 'LIVE',
    },
    {
      id: 'lt-002',
      tokenMint: 'DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263',
      tokenSymbol: 'BONK',
      tokenName: 'Bonk',
      action: 'OPEN',
      entryTimestamp: hoursAgo(18),
      entrySolAmount: 40.0,
      entryMarketCap: 850000,
      entryPrice: 0.0000000285,
      exitTimestamp: null,
      exitSolAmount: null,
      exitMarketCap: null,
      exitPrice: null,
      netPnlSol: null,
      roiPercent: null,
      holdDurationSec: null,
      archiveTag: null,
      traderMemo: 'DEV WALLET ACCUMULATING',
      currentPrice: 0.0000000641,
      currentMarketCap: 1912500,
      currentRoi: 125.0,
      status: 'LIVE',
    },
    {
      id: 'lt-003',
      tokenMint: 'EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm',
      tokenSymbol: 'WIF',
      tokenName: 'dogwifhat',
      action: 'OPEN',
      entryTimestamp: hoursAgo(1),
      entrySolAmount: 15.0,
      entryMarketCap: 3400000,
      entryPrice: 0.0034,
      exitTimestamp: null,
      exitSolAmount: null,
      exitMarketCap: null,
      exitPrice: null,
      netPnlSol: null,
      roiPercent: null,
      holdDurationSec: null,
      archiveTag: null,
      traderMemo: 'FRESH ENTRY — MOMENTUM BREAKOUT',
      currentPrice: 0.00357,
      currentMarketCap: 3570000,
      currentRoi: 5.0,
      status: 'LIVE',
    },
  ];
}

// --- Demo Closed Trades ---
const ALL_CLOSED_TRADES: ClosedTrade[] = [
  // HIMOTHY trades (10x+)
  {
    id: 'ct-001',
    tokenMint: 'mint1',
    tokenSymbol: 'MOODENG',
    tokenName: 'Moo Deng',
    action: 'CLOSED',
    entryTimestamp: daysAgo(14),
    entrySolAmount: 30.0,
    entryMarketCap: 180000,
    entryPrice: 0.00018,
    exitTimestamp: daysAgo(12),
    exitSolAmount: 390.0,
    exitMarketCap: 2340000,
    exitPrice: 0.00234,
    netPnlSol: 360.0,
    roiPercent: 1200,
    holdDurationSec: 172800,
    archiveTag: 'HIMOTHY',
    traderMemo: 'CALLED THE PUMP PRE-CT',
    status: 'CLOSED',
  },
  {
    id: 'ct-002',
    tokenMint: 'mint2',
    tokenSymbol: 'POPCAT',
    tokenName: 'Popcat',
    action: 'CLOSED',
    entryTimestamp: daysAgo(21),
    entrySolAmount: 20.0,
    entryMarketCap: 95000,
    entryPrice: 0.000095,
    exitTimestamp: daysAgo(18),
    exitSolAmount: 500.0,
    exitMarketCap: 2375000,
    exitPrice: 0.002375,
    netPnlSol: 480.0,
    roiPercent: 2400,
    holdDurationSec: 259200,
    archiveTag: 'HIMOTHY',
    traderMemo: 'ALPHA LEAK FROM INNER CIRCLE',
    status: 'CLOSED',
  },
  // PROFIT trades
  {
    id: 'ct-003',
    tokenMint: 'mint3',
    tokenSymbol: 'FARTCOIN',
    tokenName: 'Fartcoin',
    action: 'CLOSED',
    entryTimestamp: daysAgo(10),
    entrySolAmount: 15.0,
    entryMarketCap: 420000,
    entryPrice: 0.00042,
    exitTimestamp: daysAgo(9),
    exitSolAmount: 27.0,
    exitMarketCap: 756000,
    exitPrice: 0.000756,
    netPnlSol: 12.0,
    roiPercent: 80,
    holdDurationSec: 86400,
    archiveTag: 'PROFIT',
    traderMemo: 'QUICK SCALP ON VOLUME SPIKE',
    status: 'CLOSED',
  },
  {
    id: 'ct-004',
    tokenMint: 'mint4',
    tokenSymbol: 'MYRO',
    tokenName: 'Myro',
    action: 'CLOSED',
    entryTimestamp: daysAgo(8),
    entrySolAmount: 50.0,
    entryMarketCap: 1500000,
    entryPrice: 0.0015,
    exitTimestamp: daysAgo(7),
    exitSolAmount: 82.5,
    exitMarketCap: 2475000,
    exitPrice: 0.002475,
    netPnlSol: 32.5,
    roiPercent: 65,
    holdDurationSec: 86400,
    archiveTag: 'PROFIT',
    traderMemo: 'WHALE FRONT-RAN, EXITED EARLY',
    status: 'CLOSED',
  },
  {
    id: 'ct-005',
    tokenMint: 'mint5',
    tokenSymbol: 'GIGA',
    tokenName: 'GigaChad',
    action: 'CLOSED',
    entryTimestamp: daysAgo(7),
    entrySolAmount: 35.0,
    entryMarketCap: 800000,
    entryPrice: 0.0008,
    exitTimestamp: daysAgo(5),
    exitSolAmount: 59.5,
    exitMarketCap: 1360000,
    exitPrice: 0.00136,
    netPnlSol: 24.5,
    roiPercent: 70,
    holdDurationSec: 172800,
    archiveTag: 'PROFIT',
    traderMemo: 'MEME ROTATION THESIS PLAYED OUT',
    status: 'CLOSED',
  },
  {
    id: 'ct-006',
    tokenMint: 'mint6',
    tokenSymbol: 'PNUT',
    tokenName: 'Peanut',
    action: 'CLOSED',
    entryTimestamp: daysAgo(6),
    entrySolAmount: 10.0,
    entryMarketCap: 250000,
    entryPrice: 0.00025,
    exitTimestamp: daysAgo(5),
    exitSolAmount: 24.0,
    exitMarketCap: 600000,
    exitPrice: 0.0006,
    netPnlSol: 14.0,
    roiPercent: 140,
    holdDurationSec: 86400,
    archiveTag: 'PROFIT',
    traderMemo: 'SOCIAL SENTIMENT BREAKOUT',
    status: 'CLOSED',
  },
  {
    id: 'ct-007',
    tokenMint: 'mint7',
    tokenSymbol: 'BRETT',
    tokenName: 'Brett',
    action: 'CLOSED',
    entryTimestamp: daysAgo(5),
    entrySolAmount: 20.0,
    entryMarketCap: 3200000,
    entryPrice: 0.0032,
    exitTimestamp: daysAgo(4),
    exitSolAmount: 28.0,
    exitMarketCap: 4480000,
    exitPrice: 0.00448,
    netPnlSol: 8.0,
    roiPercent: 40,
    holdDurationSec: 86400,
    archiveTag: 'PROFIT',
    traderMemo: 'RIDING CEX LISTING PUMP',
    status: 'CLOSED',
  },
  {
    id: 'ct-008',
    tokenMint: 'mint8',
    tokenSymbol: 'GOAT',
    tokenName: 'Goatseus Maximus',
    action: 'CLOSED',
    entryTimestamp: daysAgo(4),
    entrySolAmount: 45.0,
    entryMarketCap: 5000000,
    entryPrice: 0.005,
    exitTimestamp: daysAgo(3),
    exitSolAmount: 72.0,
    exitMarketCap: 8000000,
    exitPrice: 0.008,
    netPnlSol: 27.0,
    roiPercent: 60,
    holdDurationSec: 86400,
    archiveTag: 'PROFIT',
    traderMemo: 'AI NARRATIVE MOMENTUM',
    status: 'CLOSED',
  },
  {
    id: 'ct-009',
    tokenMint: 'mint9',
    tokenSymbol: 'CHILLGUY',
    tokenName: 'Just a Chill Guy',
    action: 'CLOSED',
    entryTimestamp: daysAgo(3),
    entrySolAmount: 12.0,
    entryMarketCap: 600000,
    entryPrice: 0.0006,
    exitTimestamp: daysAgo(2),
    exitSolAmount: 19.2,
    exitMarketCap: 960000,
    exitPrice: 0.00096,
    netPnlSol: 7.2,
    roiPercent: 60,
    holdDurationSec: 86400,
    archiveTag: 'PROFIT',
    traderMemo: 'VIRAL MEME — TIKTOK VOLUME',
    status: 'CLOSED',
  },
  {
    id: 'ct-010',
    tokenMint: 'mint10',
    tokenSymbol: 'PENGU',
    tokenName: 'Pudgy Penguins',
    action: 'CLOSED',
    entryTimestamp: daysAgo(2),
    entrySolAmount: 30.0,
    entryMarketCap: 12000000,
    entryPrice: 0.012,
    exitTimestamp: daysAgo(1),
    exitSolAmount: 42.0,
    exitMarketCap: 16800000,
    exitPrice: 0.0168,
    netPnlSol: 12.0,
    roiPercent: 40,
    holdDurationSec: 86400,
    archiveTag: 'PROFIT',
    traderMemo: 'NFT-TO-TOKEN BRIDGE PLAY',
    status: 'CLOSED',
  },
  {
    id: 'ct-011',
    tokenMint: 'mint11',
    tokenSymbol: 'MEW',
    tokenName: 'cat in a dogs world',
    action: 'CLOSED',
    entryTimestamp: daysAgo(11),
    entrySolAmount: 18.0,
    entryMarketCap: 2100000,
    entryPrice: 0.0021,
    exitTimestamp: daysAgo(10),
    exitSolAmount: 25.2,
    exitMarketCap: 2940000,
    exitPrice: 0.00294,
    netPnlSol: 7.2,
    roiPercent: 40,
    holdDurationSec: 86400,
    archiveTag: 'PROFIT',
    traderMemo: 'CAT META ROTATION',
    status: 'CLOSED',
  },
  {
    id: 'ct-012',
    tokenMint: 'mint12',
    tokenSymbol: 'SLERF',
    tokenName: 'SLERF',
    action: 'CLOSED',
    entryTimestamp: daysAgo(9),
    entrySolAmount: 22.0,
    entryMarketCap: 780000,
    entryPrice: 0.00078,
    exitTimestamp: daysAgo(8),
    exitSolAmount: 33.0,
    exitMarketCap: 1170000,
    exitPrice: 0.00117,
    netPnlSol: 11.0,
    roiPercent: 50,
    holdDurationSec: 86400,
    archiveTag: 'PROFIT',
    traderMemo: 'BURNT LP NARRATIVE PLAY',
    status: 'CLOSED',
  },
  // REKT trades
  {
    id: 'ct-013',
    tokenMint: 'mint13',
    tokenSymbol: 'BODEN',
    tokenName: 'Jeo Boden',
    action: 'CLOSED',
    entryTimestamp: daysAgo(13),
    entrySolAmount: 15.0,
    entryMarketCap: 4500000,
    entryPrice: 0.0045,
    exitTimestamp: daysAgo(12),
    exitSolAmount: 6.0,
    exitMarketCap: 1800000,
    exitPrice: 0.0018,
    netPnlSol: -9.0,
    roiPercent: -60,
    holdDurationSec: 86400,
    archiveTag: 'REKT',
    traderMemo: 'FADED POST-DEBATE PUMP',
    status: 'CLOSED',
  },
  {
    id: 'ct-014',
    tokenMint: 'mint14',
    tokenSymbol: 'HAWK',
    tokenName: 'Hawk Tuah',
    action: 'CLOSED',
    entryTimestamp: daysAgo(6),
    entrySolAmount: 8.0,
    entryMarketCap: 2000000,
    entryPrice: 0.002,
    exitTimestamp: daysAgo(5),
    exitSolAmount: 2.4,
    exitMarketCap: 600000,
    exitPrice: 0.0006,
    netPnlSol: -5.6,
    roiPercent: -70,
    holdDurationSec: 86400,
    archiveTag: 'REKT',
    traderMemo: 'RUGPULL — DEV DUMPED',
    status: 'CLOSED',
  },
  {
    id: 'ct-015',
    tokenMint: 'mint15',
    tokenSymbol: 'TREMP',
    tokenName: 'Doland Tremp',
    action: 'CLOSED',
    entryTimestamp: daysAgo(15),
    entrySolAmount: 10.0,
    entryMarketCap: 8000000,
    entryPrice: 0.008,
    exitTimestamp: daysAgo(14),
    exitSolAmount: 7.5,
    exitMarketCap: 6000000,
    exitPrice: 0.006,
    netPnlSol: -2.5,
    roiPercent: -25,
    holdDurationSec: 86400,
    archiveTag: 'REKT',
    traderMemo: 'CUT LOSSES — TREND REVERSAL',
    status: 'CLOSED',
  },
];

export function getDemoClosedTrades(
  page: number,
  limit: number
): { data: ClosedTrade[]; totalPages: number; totalCount: number } {
  const totalCount = ALL_CLOSED_TRADES.length;
  const totalPages = Math.ceil(totalCount / limit);
  const start = (page - 1) * limit;
  const end = start + limit;
  const data = ALL_CLOSED_TRADES.slice(start, end);

  return { data, totalPages, totalCount };
}

// --- Demo Burns ---
const ALL_DEMO_BURNS: BurnRecord[] = [
  {
    id: 'burn-001',
    timestamp: hoursAgo(2),
    tradoorAmount: 125000,
    solValueAtBurn: 18.5,
    usdValueAtBurn: 2709.14,
    txSignature: '4xK9mR7vPqW3nT8yL5fH2jD6cA1bE0gN9sU3wZ7oY4rX8kJ2mQ5iF6tR1aV3pB',
    solscanUrl: formatSolscanUrl('4xK9mR7vPqW3nT8yL5fH2jD6cA1bE0gN9sU3wZ7oY4rX8kJ2mQ5iF6tR1aV3pB'),
  },
  {
    id: 'burn-002',
    timestamp: hoursAgo(8),
    tradoorAmount: 340000,
    solValueAtBurn: 50.2,
    usdValueAtBurn: 7351.29,
    txSignature: '2hF5jL8nP1qR4sT7uW0xY3zA6bC9dE2fG5hI8jK1lM4nO7pQ0rS3tU6vW9xY2z',
    solscanUrl: formatSolscanUrl('2hF5jL8nP1qR4sT7uW0xY3zA6bC9dE2fG5hI8jK1lM4nO7pQ0rS3tU6vW9xY2z'),
  },
  {
    id: 'burn-003',
    timestamp: hoursAgo(24),
    tradoorAmount: 890000,
    solValueAtBurn: 131.4,
    usdValueAtBurn: 19238.62,
    txSignature: '7mN3oP6qR9sT2uV5wX8yZ1aB4cD7eF0gH3iJ6kL9mN2oP5qR8sT1uV4wX7yZ0a',
    solscanUrl: formatSolscanUrl('7mN3oP6qR9sT2uV5wX8yZ1aB4cD7eF0gH3iJ6kL9mN2oP5qR8sT1uV4wX7yZ0a'),
  },
  {
    id: 'burn-004',
    timestamp: daysAgo(2),
    tradoorAmount: 450000,
    solValueAtBurn: 66.4,
    usdValueAtBurn: 9723.6,
    txSignature: '3aB6cD9eF2gH5iJ8kL1mN4oP7qR0sT3uV6wX9yZ2aB5cD8eF1gH4iJ7kL0mN3o',
    solscanUrl: formatSolscanUrl('3aB6cD9eF2gH5iJ8kL1mN4oP7qR0sT3uV6wX9yZ2aB5cD8eF1gH4iJ7kL0mN3o'),
  },
  {
    id: 'burn-005',
    timestamp: daysAgo(4),
    tradoorAmount: 1200000,
    solValueAtBurn: 177.1,
    usdValueAtBurn: 25926.52,
    txSignature: '9pQ2rS5tU8vW1xY4zA7bC0dE3fG6hI9jK2lM5nO8pQ1rS4tU7vW0xY3zA6bC9dE',
    solscanUrl: formatSolscanUrl('9pQ2rS5tU8vW1xY4zA7bC0dE3fG6hI9jK2lM5nO8pQ1rS4tU7vW0xY3zA6bC9dE'),
  },
  {
    id: 'burn-006',
    timestamp: daysAgo(6),
    tradoorAmount: 680000,
    solValueAtBurn: 100.3,
    usdValueAtBurn: 14689.93,
    txSignature: '5fG8hI1jK4lM7nO0pQ3rS6tU9vW2xY5zA8bC1dE4fG7hI0jK3lM6nO9pQ2rS5tU',
    solscanUrl: formatSolscanUrl('5fG8hI1jK4lM7nO0pQ3rS6tU9vW2xY5zA8bC1dE4fG7hI0jK3lM6nO9pQ2rS5tU'),
  },
  {
    id: 'burn-007',
    timestamp: daysAgo(9),
    tradoorAmount: 915000,
    solValueAtBurn: 135.0,
    usdValueAtBurn: 19769.4,
    txSignature: '1dE4fG7hI0jK3lM6nO9pQ2rS5tU8vW1xY4zA7bC0dE3fG6hI9jK2lM5nO8pQ1rS',
    solscanUrl: formatSolscanUrl('1dE4fG7hI0jK3lM6nO9pQ2rS5tU8vW1xY4zA7bC0dE3fG6hI9jK2lM5nO8pQ1rS'),
  },
  {
    id: 'burn-008',
    timestamp: daysAgo(12),
    tradoorAmount: 600000,
    solValueAtBurn: 88.5,
    usdValueAtBurn: 12958.94,
    txSignature: '8vW1xY4zA7bC0dE3fG6hI9jK2lM5nO8pQ1rS4tU7vW0xY3zA6bC9dE2fG5hI8jK',
    solscanUrl: formatSolscanUrl('8vW1xY4zA7bC0dE3fG6hI9jK2lM5nO8pQ1rS4tU7vW0xY3zA6bC9dE2fG5hI8jK'),
  },
];

export function getDemoBurns(
  page: number,
  limit: number
): { data: BurnRecord[]; totalPages: number; totalCount: number } {
  const totalCount = ALL_DEMO_BURNS.length;
  const totalPages = Math.ceil(totalCount / limit);
  const start = (page - 1) * limit;
  const end = start + limit;
  const data = ALL_DEMO_BURNS.slice(start, end);

  return { data, totalPages, totalCount };
}

// --- Demo Stream Events ---
const DEMO_STREAM_EVENTS = [
  { txType: 'SWAP' as const, description: 'Jupiter Swap: 25 SOL -> 1,250,000 $PEPE' },
  { txType: 'TAX_INFLOW' as const, description: 'Tax Inflow: 0.12 $TRADOOR received' },
  { txType: 'BURN' as const, description: 'Blast Protocol: 45,000 $TRADOOR immolated' },
  { txType: 'SWAP' as const, description: 'Jupiter Swap: 500,000 $BONK -> 52.4 SOL' },
  { txType: 'TAX_INFLOW' as const, description: 'Tax Inflow: 0.08 $TRADOOR received' },
  { txType: 'SWAP' as const, description: 'Jupiter Swap: 15 SOL -> 4,412 $WIF' },
  { txType: 'BURN' as const, description: 'Blast Protocol: 120,000 $TRADOOR immolated' },
];

export function getRandomDemoStreamEvent() {
  const event = DEMO_STREAM_EVENTS[Math.floor(Math.random() * DEMO_STREAM_EVENTS.length)];
  return {
    type: 'new-transaction' as const,
    data: {
      signature: `demo_${Date.now()}_${Math.random().toString(36).slice(2, 10)}`,
      txType: event.txType,
      timestamp: Math.floor(Date.now() / 1000),
      description: event.description,
    },
  };
}
